apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: affoio/auth
      context: py/services/auth
      docker: {}
    - image: affoio/users
      context: py/services/users
      docker: {}
deploy:
  kubectl:
    manifests:
    - "deployments/k8s/*.yaml"
    - "deployments/k8s/istio/*.yaml"
    - "deployments/k8s/jaeger/*.yaml"
    - "deployments/k8s/kiali/*.yaml"
    - "deployments/k8s/prometheus/*.yaml"
  helm:
    releases:
      - name: affo
        chartPath: deployments/helm/affo
        imageStrategy:
          helm: {}
        setValueTemplates:
          image.tag: "{{ .DIGEST_HEX }}"
        valuesFiles:
          - examples/helm/users/values.dev.yaml
          - examples/helm/users/secrets.dev.yaml
        wait: true
      - name: kiali-operator
        remoteChart: kiali-operator
        repo: https://kiali.org/helm-charts
        namespace: kiali-operator
        createNamespace: true
        wait: true
      - name: jaeger-operator
        remoteChart: jaeger-operator
        repo: https://jaegertracing.github.io/helm-charts
        namespace: jaeger-operator
        createNamespace: true
        valuesFiles:
          - deployments/helm/jaeger/operator-values.yaml
        wait: true
      - name: prometheus
        remoteChart: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        namespace: monitoring
        createNamespace: true
        valuesFiles:
          - deployments/helm/prometheus/operator-values.yaml
        wait: true
