apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "users.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "users.selectorLabels" . | nindent 8 }}
        app: {{ include "users.name" . }}
        version: {{ include "users.appVersion" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "{{ .Chart.Name }}-init"
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "job"
          - {{ include "users.fullname" . }}-migrations
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness/
              port: http
          envFrom:
            - configMapRef:
                name: affo-config
          env:
            - name: AUTH_URL
              value: http://affo-auth.{{ .Release.Namespace }}.svc.cluster.local
            - name: BILLING_URL
              value: http://affo-billing.{{ .Release.Namespace }}.svc.cluster.local
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "affo-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
          {{- if .Values.global.postgresql.existingSecret }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.postgresql.existingSecret }}
                  key: postgresql-postgres-password
          {{- else }}
            - name: DB_PASSWORD
              value: {{ .Values.global.postgresql.postgresqlPassword }}
          {{- end }}
          {{- if .Values.global.jwt.existingSecret }}
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.jwt.existingSecret }}
                  key: jwt-private-key
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.jwt.existingSecret }}
                  key: jwt-public-key
            {{- else }}
            - name: PRIVATE_KEY
              value: {{ .Values.global.jwt.privateKey }}
            - name: PUBLIC_KEY
              value: {{ .Values.global.jwt.publicKey }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
