sequenceDiagram
    participant User
    participant UserService as User Service
    participant BillingService as Billing Service
    participant OrderService as Order Service
    participant NotificationService as Notification Service
    participant MessageBroker as Message Broker

    rect rgba(0, 255, 0, .1)
        note right of User: Registre a user
        User ->> UserService: POST /register/

        activate UserService
            UserService ->> BillingService: POST /account/

            activate BillingService
                BillingService -->> UserService: 201 CREATED {account_id}
            deactivate BillingService

            UserService ->> User: 201 CREATED
        deactivate UserService
    end

    rect rgba(0, 255, 0, .1)
        note right of User: Charge a user account
        User ->> BillingService: POST /transaction/

        activate BillingService
            BillingService -->> User: 200 OK
        deactivate BillingService
    end

    rect rgba(0, 255, 0, .1)
        note right of User: Create an order
        User ->> OrderService: POST /order/
        activate OrderService
            OrderService ->> BillingService: POST /transaction/

            activate BillingService
                BillingService -->> OrderService: 200 OK
            deactivate BillingService

            OrderService ->> MessageBroker: publish
            activate MessageBroker

            OrderService -->> User: 200 OK
        deactivate OrderService

            note left of MessageBroker: OrderConfirmed
            MessageBroker -->> NotificationService: consume
        deactivate MessageBroker

        activate NotificationService
            NotificationService ->> UserService: GET /users/{user_id}

            activate UserService
                UserService -->> NotificationService: 200 OK {user_detail}
            deactivate UserService

            NotificationService ->> NotificationService: Send an email
        deactivate NotificationService
    end
