apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "affo.fullname" . }}-users
  namespace: {{ include "affo.namespace" . }}
  labels:
    {{- include "affo.labels" . | nindent 4 }}
spec:
  hosts:
  - arch.homework
  gateways:
  - {{ include "affo.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /login/
    - uri:
        prefix: /logout/
    - uri:
        prefix: /user/
    - uri:
        prefix: /register/
    route:
    - destination:
        port:
          number: 80
        host: {{ include "affo.fullname" . }}-users
