apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "affo.fullname" . }}-gateway
  namespace: {{ include "affo.namespace" . }}
  labels:
    {{- include "affo.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - arch.homework
