apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affo.fullname" . }}
  labels:
    {{- include "affo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
